version: '3.8'

services:

  backend:
    build:
      context: ./Backend
      dockerfile: ./Backend/Dockerfile
    ports:
      - "5213:5213"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  sveltekit:
    build:
      context: ./Frontend
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    restart: unless-stopped
